// Code generated by go-swagger; DO NOT EDIT.

package main

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/swag"
)

// Decision decision
// swagger:model Decision
type Decision struct {

	// potential u
	PotentialU []float64 `json:"potentialU"`

	// potential v
	PotentialV []float64 `json:"potentialV"`

	// total
	Total float64 `json:"total"`

	// volume
	// Required: true
	Volume [][]float64 `json:"volume"`
}

// MarshalBinary interface implementation
func (m *Decision) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary  interface implementation
func (m *Decision) UnmarshalBinary(b []byte) error {
	var res Decision
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
