// Code generated by go-swagger; DO NOT EDIT.

package main

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/swag"
)

// Facts facts
// swagger:model Facts
type Facts struct {

	// costs
	// Required: true
	Costs [][]float64 `json:"costs"`

	// demands
	// Required: true
	Demands []float64 `json:"demands"`

	// supplies
	// Required: true
	Supplies []float64 `json:"supplies"`
}

// MarshalBinary  interface implementation
func (m *Facts) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Facts) UnmarshalBinary(b []byte) error {
	var res Facts
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
