POST http://localhost:8080/api/find
Content-Type: application/json

{
    "demands":[70, 70, 30],
    "supplies":[30, 90, 50],
    "costs":[
        [8, 3, 1],
		[4, 7, 4],
		[5, 2, 6]
    ]
}

###

GET http://localhost:8080/api/generate?n=3d&m=3
Content-Type: application/json

###

POST http://localhost:8080/api/find
Content-Type: application/json

{
    "demands":[70, 70, 30],
    "supplies":[30, 90, 50],
    "costs":[
        [8, 3, 1],
		[4, 7, 4],
		[5, 2, 6]
    ]
}

###

GET http://localhost:8080/api/generate?ns=3d&m=3
Content-Type: application/json




